ANALYTICS_NUM = ''
SHARE_THIS_NUM = ''

NUM_PARAGRAPHS = 5
SENTENCES_PER_PARAGRAPH = (10, 15)
PHRASES_PER_SENTENCE = (1, 6)

PHRASES = [
    "tha knows",
    "by 'eck",
    "gi' o'er",
    "tha what",
    "ee by gum",
    "sup wi' 'im",
    "Michael Palin",
    "face like a slapped arse",
    "how much",
    "chuffin' nora",
    "god's own county",
    "ne'ermind",
    "th'art nesh thee",
    "where's tha bin",
    "t'foot o' our stairs",
    "gerritetten",
    "tintintin",
    "dahn t'coil oil",
    "nah then",
    "mardy bum",
    "soft southern pansy",
    "a pint 'o mild",
    "is that thine",
    "ah'll gi' thee a thick ear",
    "shurrup",
    "tha daft apeth",
    "breadcake",
    "shu' thi gob",
    "wacken thi sen up",
    "ah'll gi' thi summat to rooer abaht",
    "what's that when it's at ooam",
    "ah'll learn thi",
    "big girl's blouse",
    "soft lad",
    "tell this summat for nowt",
    "be reet",
    "where there's muck there's brass",
    "ey up",
    "bloomin' 'eck",
    "will 'e 'eckerslike",
    "any rooad",
    "bobbar",
    "aye",
    "that's champion",
    "cack-handed",
    "nay lad",
    "appens as maybe",
    "ah'll box thi ears",
    "nobbut a lad",
    'eeh',
]